name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Change this if you're using yarn or another package manager

      - name: Build Project
        run: npm run buildApp  # Ensure this outputs to `dist`

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-main@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/dist
